name: workflow name
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn test --coverage
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage
