name: workflow name
on: push
jobs:
  foobar:
    runs-on: ubuntu-latest
    steps:
      - id: set-foo
      - run: echo "foo=bar" >> $GITHUB_OUTPUT # name=value
      - run: echo ${{ steps.set-foo.outputs.foo }}
