name: workflow name
on: push
jobs:
  depoly:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          contect: .
          file: ./Dockerfile
          push: true
          tags: tlqckd0/react
          labels: latest
          
      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     builder: ${{ steps.buildx.outputs.name }}
      #     push: true
      #     tags: ${{ env.DOCKER_IMAGE }}:latest
