name: workflow name
on: push
jobs:
  foobar:
    runs-on: ubuntu-latest
    steps:
      - id: set-foo  # 1 단계 의 식별자 
        run: echo "foo=bar" >> $GITHUB_OUTPUT       # name=value
      - run: echo ${{ steps.set-foo.outputs.foo }}  # steps.<step_id>.outputs.foo | step_id : steps 의 단계 식별자
  calc:
    runs-on: ubuntu-latest
    steps:
      - id: num1  # 1 단계 의 식별자 
        run: echo "num=$(($RANDOM % 10 + 1))" >> $GITHUB_OUTPUT
      - id: num2  # 1 단계 의 식별자 
        run: echo "num=$(($RANDOM % 10 + 1))" >> $GITHUB_OUTPUT
      - run: echo $(( ${{ steps.num1.outputs.num }} + ${{ steps.num1.outputs.num }} ))
  zeroone:
    runs-on: ubuntu-latest
    steps:
      - id: num
        run: echo "num=$(($RANDOM % 2))" >> $GITHUB_OUTPUT
      - if: steps.num.outputs.num == 0
        run: echo 'zero'
      - if: steps.num.output.num == 1
        run: echo 'one'
