name: workflow name
on: push
jobs:
  depoly:
    runs-on: [self-hosted, label-go]
    steps:
      - name: docker login
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHF_TOKEN }}
          
      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     builder: ${{ steps.buildx.outputs.name }}
      #     push: true
      #     tags: ${{ env.DOCKER_IMAGE }}:latest
