name: workflow name
on: push # github event
jobs:
  echo: # jobs 식별자
    runs-on: ubuntu-latest # CI OS 환경
    steps:                 # 작업 실행 단계
      - run: echo 'Hello, Github Actions~!' # shell command
  pwd:
    name: PWD
    runs-on: ubuntu-latest
    steps:
      - name: Print Working Directory
        run: pwd
